app:
  name: angular-spring-jwt

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG
